### ISSUE TITLE
Fix numbers and lines position

### ISSUE THREAD

**Issue by vladsydorenko** [vladkampov/StepByStep.js#1]
![image](https://cloud.githubusercontent.com/assets/7015471/9009589/f2d6f7b6-37aa-11e5-94cc-be02dde114a4.png)
![image](https://cloud.githubusercontent.com/assets/7015471/9009605/01f2c5e0-37ab-11e5-88fb-23c8f4048240.png)

Please, center arrow, lines and numbers in circles.

**Comment by vladkampov** [comment]
Thx for your report, i will fix it in a few days

**Comment by vladkampov** [comment]
Already fixed. 

![image](https://cloud.githubusercontent.com/assets/7047991/9020168/35e58e40-3806-11e5-8e54-320d9dbd73df.png)
![image](https://cloud.githubusercontent.com/assets/7047991/9020170/3df02f64-3806-11e5-9176-6aa1b7fae8a4.png)

See you later, aligator c:
